/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 7.2 */
/* Fri Jan  3 08:42:51 2014 */

/* parameterized module instance */
bios2k __ (.DataInA( ), .DataInB( ), .AddressA( ), .AddressB( ), 
    .ClockA( ), .ClockB( ), .ClockEnA( ), .ClockEnB( ), .WrA( ), .WrB( ), 
    .ResetA( ), .ResetB( ), .QA( ), .QB( ));
